insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPA','GRPA-TURITA','2021/06/11 21:00:00','Turkey','TUR','Italia','ITA');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPA','GRPA-TURWAL','2021/06/16 18:00:00','Turkey','TUR','Wales','WAL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPB','GRPB-DANFIN','2021/06/12 18:00:00','Danmark','DAN','Finland','FIN');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPA','GRPA-WALSWI','2021/06/12 15:00:00','Wales','WAL','Swiss','SWI');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPB','GRPB-BELRUS','2021/06/12 21:00:00','Belgium','BEL','Russia','RUS');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPD','GRPD-ENGCRO','2021/06/13 15:00:00','England','ENG','Croatie','CRO');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPC','GRPC-NEDUKR','2021/06/13 21:00:00','Netherlands','NED','Ukraine','UKR');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPD','GRPD-AUSMKD','2021/06/13 18:00:00','Austria','AUS','Macedoine','MKD');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPD','GRPD-SCOCZE','2021/06/14 15:00:00','Scotland','SCO','Czech Republic','CZE');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPE','GRPE-SPASWE','2021/06/14 21:00:00','Spain','SPA','Sweden','SWE');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPE','GRPE-POLSLO','2021/06/14 18:00:00','Poland','POL','Slovaquia','SLO');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPF','GRPF-HUNPOR','2021/06/15 21:00:00','Hungria','HUN','Portugal','POR');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPF','GRPF-FRAGER','2021/06/15 21:00:00','France','FRA','Germany','GER');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPB','GRPB-FINRUS','2021/06/16 15:00:00','Finland','FIN','Russia','RUS');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPA','GRPA-ITASWI','2021/06/16 21:00:00','Italia','ITA','Swiss','SWI');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPB','GRPB-DANBEL','2021/06/17 18:00:00','Danmark','DAN','Belgium','BEL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPC','GRPC-UKRMKD','2021/06/17 15:00:00','Ukraine','UKR','Macedoine','MKD');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPC','GRPC-NEDAUS','2021/06/17 21:00:00','Netherlands','NED','Austria','AUS');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPE','GRPE-SWESLO','2021/06/18 15:00:00','Sweden','SWE','Slovaquia','SLO');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPD','GRPD-CROCZE','2021/06/18 18:00:00','Croatia','CRO','Czech Republic','CZE');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPD','GRPD-ENGSCO','2021/06/18 21:00:00','England','ENG','Scotland','SCO');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPF','GRPF-HUNFRA','2021/06/19 15:00:00','Hungria','HUN','France','FRA');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPE','GRPE-SPAPOL','2021/06/19 21:00:00','Spain','SPA','Poland','POL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPF','GRPF-PORGER','2021/06/18 18:00:00','Portugal','POR','Germany','GER');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPA','GRPA-ITAWAL','2021/06/20 18:00:00','Italia','ITA','Wales','WAL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPA','GRPA-SWITUR','2021/06/20 18:00:00','Swiss','SWI','Turkey','TUR');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPB','GRPB-FINBEL','2021/06/21 21:00:00','Finland','FIN','Belgium','BEL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPB','GRPB-RUSDAN','2021/06/21 21:00:00','Russia','RUS','Danmark','DAN');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPC','GRPC-UKRAUS','2021/06/21 18:00:00','Ukraine','UKR','Austria','AUS');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPC','GRPC-MKDNET','2021/06/21 18:00:00','Macedoine','MKD','Netherlands','NED');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPD','GRPD-CZEENG','2021/06/22 21:00:00','Czech Republic','CZE','England','ENG');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPD','GRPD-CROSCO','2021/06/22 21:00:00','Croatie','CRO','Scotland','SCO');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPE','GRPE-SLOSPA','2021/06/23 18:00:00','Slovaquia','SLO','Spain','SPA');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPE','GRPE-SWEPOL','2021/06/23 18:00:00','Sweden','SWE','Poland','POL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPF','GRPF-GERHUN','2021/06/23 21:00:00','Germany','GER','Hungria','HUN');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('GRPF','GRPF-PORFRA','2021/06/23 21:00:00','Portugal','POR','France','FRA');
